version: '3.8'
services:
obsidian:
image: 'ghcr.io/sytone/obsidian-remote:latest'
container_name: obsidian-remote
restart: unless-stopped
ports:
- 8080:8080
- 8443:8443
volumes:
- /opt/obsidian/vaults:/vaults
- /opt/obsidian/config:/config
environment:
- PUID=1000
- PGID=1000
- TZ=Australia/Brisbane
- DOCKER_MODS=linuxserver/mods:universal-git
- CUSTOM_PORT=8080
- CUSTOM_HTTPS_PORT=8443
- CUSTOM_USER=
- PASSWORD=
- SUBFOLDER=
